---
name: cleanup-pr-images
on:
  pull_request:
    types: [closed]
permissions: read-all
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete PR container image
        run: |
          TAG="pr-${{ github.event.pull_request.number }}"
          echo "Attempting to delete container image with tag: $TAG"
          
          # Get the package version ID for the specific tag
          PACKAGE_NAME="scenario-execution-testing"
          ORG="cps-test-lab"
          
          # List all versions and find the one with our tag
          VERSIONS=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/orgs/${ORG}/packages/container/${PACKAGE_NAME}/versions")
          
          # Find version ID with our tag
          VERSION_ID=$(echo "$VERSIONS" | jq -r ".[] | select(.metadata.container.tags[] == \"$TAG\") | .id" | head -n 1)
          
          if [ -n "$VERSION_ID" ] && [ "$VERSION_ID" != "null" ]; then
            echo "Found version ID: $VERSION_ID for tag: $TAG"
            
            # Delete the package version
            curl -L \
              -X DELETE \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/orgs/${ORG}/packages/container/${PACKAGE_NAME}/versions/${VERSION_ID}"
            
            echo "Successfully deleted container image: ghcr.io/${ORG}/${PACKAGE_NAME}:${TAG}"
          else
            echo "No container image found with tag: $TAG (this is normal if the image was never built)"
          fi
